spring:
  datasource:
    url: jdbc:mysql://localhost/testdb
    username: app
    password: apppw

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
